routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Blog\BlogController@index');
Route::get('/page/{page}', 'Blog\BlogController@show')->name('page');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
Route::get('/register', 'Admin\AdminController@redirect');
Route::get('/password/reset', 'Admin\AdminController@redirect');
Route::get('/admin', 'Admin\AdminController@admin');

Route::group(['middleware'=>'auth', 'prefix'=>'admin'],function () {
//    Route::get('/create', 'Admin\PagesController@create')->name('create-page');
//    Route::post('/create-page', 'Admin\PagesController@store');
    Route::resource('/pages', 'Admin\PagesController');
});

app/Page.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    protected $fillable = ['title', 'slug', 'parent_id', 'post'];

    public function parents()
    {
        return $this->belongsTo('App\Page', 'parent_id');
    }

    public function children()
    {
        return $this->hasMany('App\Page', 'parent_id')->get();
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AdminController extends Controller
{
    public function redirect(){
        return redirect()->to('/');
    }

    public function admin(){
        if (Auth::check()){
            return redirect()->to('/admin/pages');
        } else {
            return view('auth.login');
        }
    }
}

app/Http/Controllers/Admin/PagesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Page;

class PagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = Page::orderBy('created_at', 'desc')->get();
        return view('admin.pages.index')->with('pages', $pages);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pages = Page::get(['id', 'title']);

        return view('admin.pages.create')->with('pages', $pages);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Page $page, Request $request)
    {
        $page->create($request->all());

        return redirect()->route('pages.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page = Page::find($id);
        $pages = Page::get(['id', 'title']);
        return view('admin.pages.edit')->with('page', $page)->with('pages', $pages);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Page $page)
    {
//        dd($request->all());
        $page->update($request->all());

        return redirect()->route('pages.index')
        ->with('success','Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $page = Page::find($id);
        $page->delete();

        return redirect()->route('pages.index')
            ->with('success','Product deleted successfully');
    }
}

app/Http/Controllers/Blog/BlogController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;
use App\Page;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = Page::where('parent_id', 0)->orderBy('created_at', 'desc')->get();

        return view('index')->with('pages', $pages);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $page = Page::where('slug', $slug)->first();
        $pages = Page::where('parent_id', 0)->orderBy('created_at', 'desc')->get();

        return view('inner')->with('page', $page)->with('pages', $pages);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/admin/components/admin-nav.blade.php
<nav>
    <div class="admin-menu-item">
        <a href="{{route('pages.index')}}">
            PAGES
        </a>
    </div>
    <div class="admin-menu-item">
        <a href="{{route('pages.create')}}">
            CREATE PAGE
        </a>
    </div>
</nav>

resources/views/admin/components/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ config('app.name', 'Laravel') }}</title>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}" defer></script>
<script src="{{ asset('js/tinymce/tinymce.min.js') }}"></script>

<!-- Fonts -->
<link rel="dns-prefetch" href="//fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

<!-- Styles -->
<link href="{{ asset('css/app.css') }}" rel="stylesheet">

resources/views/admin/components/scripts.blade.php
<script type="text/javascript">
    tinymce.init({
        selector : "textarea",
        height: 500,
        plugins : ["advlist autolink lists link image charmap print preview anchor", "searchreplace visualblocks code fullscreen", "insertdatetime media table contextmenu paste jbimages"],
        toolbar : "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image jbimages",
    });
</script>

resources/views/admin/home.blade.php
@extends('layouts.admin-app')

@section('content')

@endsection

resources/views/admin/pages/create.blade.php
@extends('layouts.admin-app')

@section('content')
<form method="post" action="{{route('pages.store')}}">
    @csrf
    <div class="form-group">
        <label for="exampleFormControlInput1">Page title</label>
        <input class="form-control" name="title" type="text" placeholder="Page title">
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Slug</label>
        <input class="form-control" name="slug" type="text" placeholder="Slug">
    </div>
    <div class="form-group">
        <label for="exampleFormControlInput1">Page parrent</label>
        <select class="form-control" name="parent_id">
            <option value="0">None</option>
            @foreach($pages as $page)
            <option value="{{$page->id}}">{{$page->title}}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Post</label>
        <textarea class="form-control post" id="exampleFormControlTextarea1" name="post" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-info">Create</button>
</form>

@endsection

resources/views/admin/pages/edit.blade.php
@extends('layouts.admin-app')

@section('content')
    <form method="post" action="{{route('pages.update', $page->id)}}">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="exampleFormControlInput1">Page title</label>
            <input class="form-control" name="title" type="text" placeholder="Page title" value="{{$page->title}}">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Slug</label>
            <input class="form-control" name="slug" type="text" placeholder="Slug" value="{{$page->slug}}">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Page parrent</label>
            <select class="form-control" name="parent_id">
                <option value="0">None</option>
                @foreach($pages as $item)
                    @if($page->parent_id == $item->id)
                        <option value="{{$item->id}}" selected>{{$item->title}}</option>
                    @else
                        <option value="{{$item->id}}">{{$item->title}}</option>
                    @endif
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Post</label>
            <textarea class="form-control editor" id="exampleFormControlTextarea1" name="post" rows="5">{!!$page->post!!}</textarea>
        </div>
        <button type="submit" class="btn btn-info">Save</button>
    </form>
@endsection

resources/views/admin/pages/index.blade.php
@extends('layouts.admin-app')

@section('content')
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Page title</th>
            <th scope="col">Page url</th>
            <th scope="col">Post</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($pages as $key => $value)
        <tr>
            <th scope="row">{{$key+1}}</th>
            <td>{{$value->title}}</td>
            <td>{{$value->slug}}</td>
            <td>{{$value->post}}</td>
            <td class="d-flex">
                <a class="btn btn-warning action-button" href="{{route('pages.edit', $value->id)}}">Edit</a>
                <form method="post" action="{{route('pages.destroy', $value->id)}}">
                    @csrf
                    @method('delete')
                    <button class="btn btn-danger action-button ml-2" type="submit">Delete</button>
                </form>

            </td>
{{--            <td></td>--}}
        </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">

            </div>
        </div>
    </div>
@endsection

resources/views/inner.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center inner">
            <div class="col-md-12">
                <div class="mx-3 my-5">
                {!! $page->post !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/admin-app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
@include('admin.components.head')
</head>
<body>
    <div id="app">
        <main class="py-4 px-4">
            <div class="row">
                <div class="col-md-2 admin-menu">
                    @include('admin.components.admin-nav')
                </div>
                <div class="col-md-10">
                    @yield('content')
                </div>
            </div>
        </main>
    </div>
@include('admin.components.scripts')
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        @include('components.nav')

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>